### ISSUE TITLE
SublimeText allow some typing error

### ISSUE THREAD

**Issue by shuax** [farzher/fuzzysort#1]
![123](https://user-images.githubusercontent.com/6940583/29603414-a60d94f8-8816-11e7-92e5-0f65f5041a7f.png)
like this

**Comment by farzher** [comment]
Yeah, it seems to allow a single transpose. I was aware of this but didn't attempt it because I wanted to go fast.

Thsi wolud be a uesful opiton thuogh; I'll look into it!
