### ISSUE TITLE
Using a key whose value is an array

### ISSUE THREAD

**Issue by n8sb** [farzher/fuzzysort#102]
I have an object with a key called "tags" whose value is an array of tags:

```
const allResources = {name: foo, tags:["123","abc"]};
const searchTerm = e.target.value;
const results = fuzzysort.go(searchTerm, allResources, { key: "tags" }); // "tags" is an array
console.log(results); // [total: 0]
```

I am able to search an array directly, but when the array is within an object, the return value is "[total: 0]".

Is there a way to make this work?

**Comment by n8sb** [comment]
Excellent.  Thanks for the help and the package!

**Comment by alinnert** [comment]
I found another solution: You can add a getter that groups everything that should be searchable into a single string:

``` js
const allResources = [
  { name: 'foo', tags: ['123', 'abc'] }
]

const searchableResources = allResources.map((item) => {
  return {
    ...item,
    get searchString() {
      // This creates the string "foo 123 abc"
      return `${item.name} ${item.tags.join(' ')}`
    }
})

fuzzysort.go('abc', searchableResources, { key: 'searchString' })
```

But honestly, what I'd find really handy is a new option that does what `get searchString` does. Something like this:

``` js
fuzzysort.go('abc', allResources, {
  filterValue(item) {
    return `${item.name} ${item.tags.join(' ')}`
  }
})
```

That would make the library more flexible. And in TS it wouldn't be necessary to introduce a new type for `typeof allResources & { readonly searchString: string }`.

**Comment by farzher** [comment]
> But honestly, what I'd find really handy is a new option that does what `get searchString` does. Something like this:

i'd rather not have more features if they're not necessary. your solution seems pretty good. i often just add a search key to my objects, although this does mutate the objects

```js
const allResources = [{name: 'foo', tags: ['123', 'abc']}]
allResources.forEach(it => it.key = `${it.name} ${it.tags.join(' ')}`)
fuzzysort.go('abc', allResources, {key: 'key'})
```

your `filterValue` does seem quite simple and useful. if you're using `filterValue`, you wouldn't also be using `key`, so i could probably just allow key to be a remapping function like this

```js
const allResources = [{name: 'foo', tags: ['123', 'abc']}]
fuzzysort.go('abc', allResources, {
  key: it => `${it.name} ${it.tags.join(' ')}`
})
```

**Comment by farzher** [comment]
`key` can now be a function in fuzzysort v3

```js
const allResources = [{name: 'foo', tags: ['123', 'abc']}]
fuzzysort.go('abc', allResources, {key: obj => obj.tags?.join()})
```

**Comment by Leftium** [comment]
I used the fact `keys` can be object paths to search an array of strings:
```
const keys = [
  'name',
  'tags.0',
  'tags.1',
  'tags.2',
  'tags.3',
  // Keep adding paths as needed.
]
const allResources = {name: foo, tags:["123","abc"]};
const results = fuzzysort.go('search term', allResources, { keys }); // "tags" is an array
```

Differences vs concatenating into a single string:
- You are limited to a finite number of tags,
- But I find the scores tend to be more accurate (like 1.0 for exact match).
- Also it is easier to isolate each highlighted array item by itself.

Links:
- [Source code ](https://github.com/Leftium/zbang/blob/c67c51cfd6081db12daeec9bd5f53bfff51f7660/kit/src/routes/%2Bpage.svelte#L49-L100)
- Live demo: https://zz.leftium.com/
