### ISSUE TITLE
error in typescript while attempting to map after search

### ISSUE THREAD

**Issue by Claudi0-V** [farzher/fuzzysort#107]
first of all, I really appreciate your work and how awesome this lib is.

i'm trying to simply map after doing a search/sort like this:
```ts
const fuzzySearchRules = { limit: 15, key: "value" };

export function fuzzySearch(searchTerm, targets, rules = fuzzySearchRules) {
	const results = fuzzysort
		.go(searchTerm, targets, rules)
		.map(({ obj }) => obj);
	return results;
}
```
and I'm getting this error:
```
error TS2339: Property 'obj' does not exist on type 'Result'.

.map(({ obj }) => obj);

```
maybe is because i'm new to typescript, but I can't seem to solve this problem

**Comment by farzher** [comment]
i'm guessing that's because typescript doesn't know what `rules` is exactly.
`go` returns different types of results depending on the options.
maybe call go like `.go(searchTerm, targets, {key: ''/*so ts knows we're using the key option*/, ...rules})`

**Comment by Claudi0-V** [comment]
it was this indeed. sorry for this and I really appreciate your help
