### ISSUE TITLE
Option to ignore punctuation?

### ISSUE THREAD

**Issue by DavidAtImpactCubed** [farzher/fuzzysort#108]
Firstly, thank you for a great library. It has made it incredibly easy to implement client side searching of lists of objects.

We stumbled upon a use case where it could perhaps work even better: where differences in punctuation throw the search.

In our particular case, a search for:

> Something in the U.S.

does not match

> Something in the US

Perhaps an options flag "ignorePunctuation" which removes all punctuation from both the query and the values would help deal with this case?

**Comment by farzher** [comment]
so, i receive these requests for simple options often.

personally i think writing the little piece of code i need is better than reading library documentation to find what i'm looking for.

does options.ignorePunctuation remove `'`? what's considered punctuation? i don't want to learn how a library works.

sorry for the rant; just giving an explanation for why i've been ignoring almost all feature requets / pull requests.

normally i'd implement the option as a snippet of js for anyone who lands on this page, but i'm not sure what exactly should be ignored.

here's the solution for that case at least:

```
let stripPeriods = s => s.replace(/[\.]/g, "")
let search = 'Something in the U.S.'
let targets = ['Something in the US']
fuzzysort.go(stripPeriods(search), targets)
```

**Comment by DavidAtImpactCubed** [comment]
Not at all, thanks for responding.

In our case we're using an object with a list of keys, so the code needed to pre-transform the targets would be a little more involved, but the principle holds.

That said, the main motivation for wanting to avoid transforming the targets is that we use the output of the sort call directly, and we don't want this output to be transformed. We could  maybe map the outputs back to the original objects using an ID field, but then our implementation is no longer a reusable without becoming a lot messier.

I totally understand the desire to avoid lots of flags for small (and perhaps opaque) variations in behaviour. What about a generic extension point for users to hook into to pre-transform target text and query? Something like a function on options: preSortTextTransform. Such a function could be used by some to normalise umlauts, by others to remove punctuation, or do whatever quirk of functionality they need without needing to mutate their targets?

**Comment by farzher** [comment]
why do you have to edit targets? you can simply edit their search (like in my example code). it's true the dots won't be highlighted, but is that a problem?

**Comment by DavidAtImpactCubed** [comment]
Ideally, it would work either way (a search for US matches U.S. and a search for U.S. returns US). As I understand it, without going into changes in the library that means mutating the targets (and then remapping the output back to the original objects). The same challenge applies to those looking to normalise diacritics or accents, as in the PR raised by jove4015, which is people are looking for solutions by changing the library behaviour. Have I misunderstood?

A hook function might meet those needs without needing to build custom logic for each variant. I'd be happy to have a crack at a PR if you think it fits with your vision for the library, but obviously I don't want to waste my time if you don't agree.

**Comment by farzher** [comment]
i don't think that's a bad idea. i just don't think it's a common enough thing to be worth adding the complexity.

if people want to make a fuzzysort fork with lots of convenience features that's cool though. i'd even link to it on the readme.
