### ISSUE TITLE
Trying to use nested keys

### ISSUE THREAD

**Issue by jmontanholi** [farzher/fuzzysort#109]
First of all, this is an amazing library, great work!

Is there a way to use nested keys? So for example,

we have this object:
```
block: {
  something: {
    otherthing: {
      name: 'some name'
    }
  }
}
```

can I do something similar to `fuzzysort.go(searchName, blocks, {key: nestedNameKeyHere, treshold: -10000,});`
or I will need to sort it and then do a filter?

Thanks again for the awesome library!

**Comment by farzher** [comment]
```
{key: 'block.something.otherthing.name'}
```
or
```
{key: ['block', 'something', 'otherthing', 'name']}
```

**Comment by jmontanholi** [comment]
Thank you so much!
