### ISSUE TITLE
Sorting data that is stored as SoA (Structures of Arrays) as opposed to AoS (Arrays of Structures)

### ISSUE THREAD

**Issue by sumzary** [farzher/fuzzysort#113]
If I have an array ids[1000] and an array names[1000],
currently, I have to create an intermediate array of objects[{ id, name },{}...]
in order to be able to sort by names, and have access to the id as well.

**Comment by farzher** [comment]
> currently, I have to create an intermediate array of objects[{ id, name },{}...]

yup. what's the problem?
here's an optimized way to do it by attaching your id to an internal fuzzysort object to avoid creating new garbage objects

```js
ids = new Array(1000)
names = new Array(1000)
names[69] = 'steve'

var results = fuzzysort_aos('steve', names)
var name = results[0].target
var id   = results[0].index
console.log(name, id)

function fuzzysort_aos(search, names, options) {
  var prepared_array = []
  for(var i=0; i<names.length; i++) {
    prepared_array[i] = fuzzysort.prepare(names[i])
    prepared_array[i].index = i
  }
  return fuzzysort.go('steve', prepared_array, options)
}
```
