### ISSUE TITLE
What's the point of returning your name

### ISSUE THREAD

**Issue by samuel-pipelaunch** [farzher/fuzzysort#115]
Hi, I've been using your great library for almost one year. Last month I was checking the updated 2.x version and found this code:

https://github.com/farzher/fuzzysort/blob/c7f1d2674d7fa526015646bc02fd17e29662d30c/fuzzysort.js#L28

![image](https://user-images.githubusercontent.com/96358868/206877857-4a24d498-52cc-40ed-ae08-afa6d42a1e73.png)

There's any reason to have this type of "easter eggs"?
Now I become very concerned of what else could be included on this search library before using it on production projects

Keep the great work!

**Comment by farzher** [comment]
> Now I become very concerned of what else could be included on this search library before using it on production projects

good! anything can be added to any library at any time!
if this egg serves as a reminder, that's cool. take on dependencies and updates with caution
