### ISSUE TITLE
v1.0 changes feedback/suggestions

### ISSUE THREAD

**Issue by farzher** [farzher/fuzzysort#12]
This is a list of changes I'm considering for v1.0, feel free to give feedback/suggestions

1. Invert the score to be negative, so that higher scores are better.
2. Remove the option to automatically highlight and expose `fuzzysort.highlight(result)`
3. Move options from `fuzzysort.limit = 1` to `fuzzysort.go(search, targets, {limit: 1})`
4. Add ability to search objects by `key` or `keys`:

```js
fuzzysort.go(search, objects, {key: 'title'})

fuzzysort.go(search, objects, {
  keys: ['title', 'desc'],
  scoreFn: (a) => Math.max(a[0]?a[0].score:-Infinity, a[1]?a[1].score-100:-Infinity) // optional
})
```

**Comment by aquadk** [comment]
I really do not like the new version. There is too much logic about the data object in the code now.
Could be very simple, could just have been a function to retrieve a search string from an object. Then the feature could be part of the settings. In the result, the object could only be part of the list.

**Comment by farzher** [comment]
I don't understand. What exactly is the issue? What part of the API is bad and what should it be replaced by?

**Comment by aquadk** [comment]
just like `var scoreFn = options.scoreFn || defaultScoreFn.`

Then you can insert a function into fuzzysort. Like:

function myGetStringFunc(obj)
{
  return obj.value1 +' '+ obj.value2;
}
