### ISSUE TITLE
Support non-English characters

### ISSUE THREAD

**Issue by edengby** [farzher/fuzzysort#121]
I tried to running fuzzysort.single and fuzzysort.go on Hebrew characters and it returned null.
Is it possible to support non-English characters?

Thanks.

**Comment by farzher** [comment]
example? seems to work fine. this returns a result

`fuzzysort.go('(עִבְרִי,', ['(Hebrew: אָלֶף־בֵּית עִבְרִי, Alefbet ivri), known'])`
