### ISSUE TITLE
Link in the "About" section is broken.

### ISSUE THREAD

**Issue by BenJackGill** [farzher/fuzzysort#123]
The link you have is this: https://rawgit.com/farzher/fuzzysort/master/test.html

But it should be this: https://rawgit.com/farzher/fuzzysort/master/test/test.html

I am talking about this link here in About sidebar:

<img width="1418" alt="Screenshot 2023-05-09 at 12 52 50 pm" src="https://user-images.githubusercontent.com/2043257/237006265-4a5f516b-147a-4bff-b91c-b81f67bb844c.png">

**Comment by farzher** [comment]
thank you!
