### ISSUE TITLE
Even when the threshold is -Infinity there is filtering happening.

### ISSUE THREAD

**Issue by buckmaxwell** [farzher/fuzzysort#124]
Even when the threshold is -Infinity there is filtering happening. I need to preserve the entire set I am sorting -- I just want to sort it. Can I do that?

**Comment by farzher** [comment]
no. if it's not a match it won't be returned. but you can simply manually add everything else back into the end of your results.

**Comment by hugo082** [comment]
Having an empty result for `fuzzysort.go('Value Abc', ['Value', 'Other'], { threshold: -Infinity })` seems incoherent to me

**Comment by farzher** [comment]
> Having an empty result for `fuzzysort.go('Value Abc', ['Value', 'Other'], { threshold: -Infinity })` seems incoherent to me

yeah i understand, but this is how sublime text works so i'm not considering it an issue for now
