### ISSUE TITLE
Return type of `fuzzysort.indexes` seems wrong

### ISSUE THREAD

**Issue by eramdam** [farzher/fuzzysort#128]
I've been using 1.x and I'm now upgrading to the 2.x version of the library and I noticed a change in the type of `indexes`. It seems it's defined as `ReadonlyArray<Number>` ([see](https://github.com/farzher/fuzzysort/blob/master/index.d.ts#L79)), is that expected? Previously it was defined as `ReadonlyArray<number>` so it feels like a mistake.

**Comment by farzher** [comment]
thank you. and get ready to upgrade to v3.0 👀
