### ISSUE TITLE
New version needs docs + examples

### ISSUE THREAD

**Issue by rglover** [farzher/fuzzysort#129]
Was surprised to see a new release of this. I love this package but the changes to the API in the new version are fairly confusing and the documentation is missing a lot of details (I had to roll back to 2.0.4 because the new highlight API seems more complex than the previous).

Happy to work with you on the docs if you'd like/it would help. Send me an email and we can figure it out: ryan.glover@cheatcode.co.

**Comment by farzher** [comment]
`fuzzysort.highlight(result)` changed to `result.highlight()`

the readme shows that. what's confusing?

**Comment by rglover** [comment]
It does, but it doesn't work as described. If I loop over the `results` returned by `fuzzysort.go()` and then call `result.highlight()` on a result I get "`result.highlight()` is undefined." There seems to be some connection/usage of `fuzzysort.single()` required but it's not immediately clear from the docs.

This happens locally in an app as well as in the replit env in the screenshot below.

<img width="1167" alt="Screenshot 2024-05-16 at 1 00 09 PM" src="https://github.com/farzher/fuzzysort/assets/874210/0ac35fcf-cc67-411e-bff4-b147ade576f7">

Writing tutorials for stuff like this is my bread and butter—happy to collab and help come up with some solid examples. This is a really great library.

**Comment by JJCUBER** [comment]
@rglover I took a quick look by logging `result` to console, and it seems that the actual "object" is instead stored with the key `0` when you instead have custom keys (i.e. what you are searching over are objects).

**Comment by JomMarn** [comment]
I got this error too. My workaround is to call result[0].highlight() before mapping it into a new object, like this:
```javascript
const formatted_result = results.map((result={}) => {
    let result0 = result[0].highlight();
    let result1 = result[1].highlight();
    return {
      ...(result?.obj || {}),
      hilighted_result0: result0,
      hilighted_result1: result1
    };
});
```

**Comment by rglover** [comment]
Thanks @JJCUBER and @JomMarn, I'll take a look.

**Comment by JomMarn** [comment]
Hey @rglover, I just updated to version 3.0.1, which was released two weeks ago, and it is working fine now. There's no need to call result.highlight() before mapping to new object anymore for me.

**Comment by sebastianvitterso** [comment]
@rglover Can this be closed?

**Comment by rglover** [comment]
Yes 👍
