### ISSUE TITLE
Any option / method for whole string matching only

### ISSUE THREAD

**Issue by Gervwyk** [farzher/fuzzysort#13]
How would one match a whole string only?

For example, if the search string is `find` only match give the matches which contains the entire `find` phrase, not `f`, `i` , `n` and `d` combinations. 
I tried determining this  from the score without much success.

**Comment by farzher** [comment]
What's the point of doing that? That's not very fuzzy.

If I understand you correctly, you could do that with 1 line of vanilla js:
```
var targets = ['fxixnxd', 'xxxxfindxxxx']
targets.filter((t) => ~t.indexOf('find'))
```

**Comment by farzher** [comment]
What you want is way too simple. It's also pretty different, the current scoring/highlighting algos would be overkill/inefficient.

There's no reason to add it as an option here. Here's all your code, including sorting and highlighting:

```js
var search = 'find'
var targets = ['FirstIndexfinder', 'fxixnxd', 'xxxxfindxxxx']
targets.filter(t => ~t.indexOf(search))
  .sort(t => t.indexOf(search))
  .map(t => {
    var i = t.indexOf(search)
    return `${t.substr(0, i)}<b>${t.substr(i, search.length)}</b>${t.substr(i+search.length)}`
  })
```

Feel free to turn it into your own module `lessfuzzysort` ;)

**Comment by Gervwyk** [comment]
Thanks @farzher for the great advise! This makes sense.
