### ISSUE TITLE
Score is returned as negative at 3.0.2

### ISSUE THREAD

**Issue by khanhdo16** [farzher/fuzzysort#135]
First of all, thank you for publishing this library.
I just found this library and tested it out, but when I tried to logs the example in the docs, the score values were actually negative number, not a float like described in the changelog

<img width="556" alt="Screenshot 2024-08-18 at 11 42 59 PM" src="https://github.com/user-attachments/assets/620d4b85-1673-4523-aa9c-25535c9fd3b9">

**Comment by farzher** [comment]
you want to use `result.score` not `result._score`
i agree that log output looks a bit confusing though

**Comment by khanhdo16** [comment]
Oh, thank you for explaining, I didn't see `_score` being mentioned in the docs. I thought `score` and `_score` are the same. It'd be helpful if it's mentioned in the docs
