### ISSUE TITLE
Duplicate results

### ISSUE THREAD

**Issue by parkerpearson** [farzher/fuzzysort#18]
Hi there,

I'm using fuzzysort on an array of objects with the `key` object to choose the property of the objects to match against. Some of the objects have the same value in this property, but different values in other properties.

As expected, search terms that match one of these objects also matches the others. My issue is that drilling into the originating object with `result.obj` only ever points to one of the original objects, rather than the separate instances.

See example code below (or [codepen here](https://codepen.io/parker_pearson/pen/ooPoxX?editors=0011)):

```js
var targets = [
  {name: 'Typography', version: '3.1.0'},
  {name: 'Typography', version: '2.1.0'}
]
var results = fuzzysort.go('typography', targets, {key: 'name'})
console.log(results[0].obj.version, results[1].obj.version)

// expected output "3.1.0" and "2.1.0", got output of "3.1.0" and "3.1.0"
```

**Comment by farzher** [comment]
ty!

this is caused by a performance optimization that apparently only makes sense when not using keys.

easy fix is to remove that optimization for keys. I'll try to find a more clever fix though.

**Comment by parkerpearson** [comment]
Great, thanks! Will try to test this in my use case next week.

**Comment by parkerpearson** [comment]
Yep, looks like this worked. Thanks.

**Comment by snocoder** [comment]
what is the final query you have written to fix this?
because I am also facing this issue.
