### ISSUE TITLE
useless condition

### ISSUE THREAD

**Issue by Yuyz0112** [farzher/fuzzysort#2]
```js
const wouldSkipAhead = matchesSimple[searchI] > targetI
  if(wouldSkipAhead) {
    const nextMatchIsNextTarget = matchesSimple[searchI] === targetI
    if(!nextMatchIsNextTarget) {
      // skip and backfill history
      targetI = matchesSimple[searchI]
      isConsec = false
      const targetCode = target.charCodeAt(targetI-1)
      wasUpper = targetCode>=65&&targetCode<=90
      wasAlphanum = wasUpper || targetCode>=97&&targetCode<=122 || targetCode>=48&&targetCode<=57
    }
  }
```
Is there any situation that `nextMatchIsNextTarget` is `true` while `wouldSkipAhead` is `true`?

**Comment by farzher** [comment]
Thanks, this is definitely useless. Possibly a copy/paste error.

Can you check the line of code that says `// TODO: removing this doesn't break tests` and tell me why that seems to be useless too? lol

**Comment by farzher** [comment]
I was able to make a test that broke the `// TODO: removing this doesn't break tests` line of code.
