### ISSUE TITLE
obj property is always null

### ISSUE THREAD

**Issue by kohsah** [farzher/fuzzysort#20]
I have an array like this: 
```
 [ { value: '2MoisDePréavis',
    count: '1',
    label: '2 mois de préavis' },
  { value: 'AbandonDePoste',
    count: '1',
    label: 'Abandon de poste' },
  { value: 'Abandonnait', count: '1', showAs: 'Abandonnait' },
  { value: 'AbusiveDeContrat',
    count: '1',
    label: 'Abusive de contrat' },
  { value: 'AbusiveDuContrat',
    count: '1',
    label: 'Abusive du contrat' } ]
``` 
When i run the fuzzysort, the result object in the promise always has the obj value returned as null
``` javascript
fuzzysort.goAsync("Aba", arr, {keys: ['label']}).then(.....)
```
In fuzzysort goAsync the obj value is not null when set ( i console logged it ) . 
 
I am running this on the server side (Node JS 8.9)

**Comment by farzher** [comment]
?

The example data you provided crashes because one object doesn't have any label. Is that your issue?

If i remove that object, `obj` always seems fine.

**Comment by kohsah** [comment]
Sorry , the label missing was a copy and paste issue. I have all the labels correctly set -- not really sure why the obj is always set to null.

**Comment by farzher** [comment]
idk, give the exact code
