### ISSUE TITLE
Support for ancient browsers

### ISSUE THREAD

**Issue by aperkins81** [farzher/fuzzysort#21]
Hi, While testing on Internet Explorer 11 the following error appears in the console:

Object doesn't support property or method 'assign'

https://github.com/farzher/fuzzysort/blob/b77b533e39719975123c3667241961af408e0f97/fuzzysort.js#L549

**Comment by farzher** [comment]
Let me know if there's another issue or if it's good now.

**Comment by aperkins81** [comment]
Still an issue, now it's complaining about a missing semicolon (no line number in the debugger, of course).

We're now thinking of offering a non-fuzzy simple-search to internet explorer users.

If you're keen on getting fuzzysort to work, the VirtualBox VM's for IE11 etc are useful (though you have to look through current Issues to get it to work)

https://github.com/xdissent/ievms
