### ISSUE TITLE
how to highlight when using fuzzysort.go() with array of targets?

### ISSUE THREAD

**Issue by leroy0211** [farzher/fuzzysort#22]
As far as I can see, there is no possibility to highlight the data, when using .go with an array of targets.

My use case: 
```
let search = 'abl';

let data = [{ label: "Label A", value: 1},{ label: "Label B", value: 2}];

let sorted = fuzzysort.go(search, data, {
   keys: ['label']
}).map(d => d.obj);  // convert back to the original data array

```

Now i want to highlight the data, in the `sorted` variable. 

```
[{ label: "L<b>ab</b>e<b>l</b> A", value: 1},{ label: "L<b>ab</b>e<b>l</b> B", value: 2}]
```

My suggestion is to extend the `options` object, with a highlight property. So it will still be performant enough.

**Comment by leroy0211** [comment]
Currently I've fixed it like this: 

```
let search = 'abl';
let data = [{ label: "Label A", value: 1},{ label: "Label B", value: 2}];

let sorted = fuzzysort.go(search, data, {key:'label'}).map(e => ({
   ...e.obj, 
   label: fuzzysort.highlight(e)
} ));

```

That will give me the desired output, but it's kinda hacky I think.

**Comment by farzher** [comment]
adding highlight as a option slows down the search a bit even when not using highlight.

`fuzzysort.single` has no options so requires you to use `fuzzysort.highlight` anyway.

highlight has arguments, what would the highlight option look like?
`highlight:true` and `highlight:['<span>', '</span>']` i guess?

why not just do:
```
let results = fuzzysort.go(...)
results.forEach(r => r.highlighted = fuzzysort.highlight(r))
```

that should be the same performance as a built in option, and it's not too messy.

i'll look at benchmarks to see what makes sense.

**Comment by farzher** [comment]
i couldn't find any performance benefit from making highlight an option.
closing this for now.
