### ISSUE TITLE
Non-ascii chars?

### ISSUE THREAD

**Issue by davidgfnet** [farzher/fuzzysort#23]
Does this thing work well with non-ascii charts? Have the feeling it breaks as soon as one starts adding utf-8 chars like accents or similar chars.

**Comment by farzher** [comment]
it seems to work fine.
you can play with it here using browser dev tools. https://rawgit.com/farzher/fuzzysort/master/test.html

![image](https://user-images.githubusercontent.com/1005136/36348007-7c483456-1435-11e8-9b55-18d58bd58e6d.png)

`a` and `ä` are considered different characters if that was your question. but you can just manually normalize the search/targets to solve that

**Comment by farzher** [comment]
```javascript
var removeAccents = it => it.normalize('NFD').replace(/[\u0300-\u036f]/g, '')

var search = 'u'
var raw_targets = ['Zürich', 'oober', 'pikachu', 'Über']
var targets = raw_targets.map(t=>({original:t, normalized:removeAccents(t)}))

fuzzysort.go(removeAccents(search), targets, {key:'normalized'})
  .map(r=>r.obj.original) // ["Über", "Zürich", "pikachu"]
```

**Comment by davidgfnet** [comment]
Uh I see. In my test I have an entry (3 words) with one accent, and when searching for the exact text without the accent it doesn't even cut the threshold (no results). I will definitely try some normalization of "equivalent" characters, but I find it weird that one char mismatch blows it up. 
Will investigate more and report back :) Thanks!

**Comment by farzher** [comment]
that's how this search works. every search character has to be in the target, in sequence. the only typo allowed is a single transpose.

**Comment by nol13** [comment]
i mean, if you want to be pedantic about it, the single transpose allowance is broken for astral codepoints. not that it really matters for this or that there's a good way to fix it without killing performance.

good stuff though, just threw this into prod.
