### ISSUE TITLE
How to perform fuzzySort if the key is an Array of Strings?

### ISSUE THREAD

**Issue by rinav** [farzher/fuzzysort#25]
What I am trying to do is, try to guess if the searchString matches in the `array of names`. It does not matter if it matches any of the names. If it matches I would like to get it's category.

`categories json`

    [        
       {
            "category": "Akshay Kumar",
            "names": [
                "Akshay Kumar",
                "Khiladi",
                "Akki"
            ]
        },
        {
            "category": "Aamir Khan",
            "names": [
                "Aamir Khan",
                "A.K.",
                "Mr. Perfectionist",
                "Tom Hanks of India"
            ]
        }
    ]

    const fuzzyConfig = {
      key: 'names',
      allowTypo: true,
      limit: 10
    };

I am getting below error, not sure if the below stack would be helpful

    if (target._targetLowerCodes.length === 0) continue
                                        ^

      TypeError: Cannot read property 'length' of undefined
    at Object.go(/run/media / rinav / workspace / nodeProjects / random / node_modules / fuzzysort / fuzzysort.js: 107: 39)
    at / run / media / rinav / workspace / nodeProjects / random / fuzzySort.js: 44: 29
    at Object.<anonymous>(/run/media / rinav / workspace / nodeProjects / random / fuzzySort.js: 52: 2)
    at Module._compile(module.js: 662: 30)
    at Object.Module._extensions..js(module.js: 673: 10)
    at Module.load(module.js: 575: 32)
    at tryModuleLoad(module.js: 515: 12)
    at Function.Module._load(module.js: 507: 3)
    at Function.Module.runMain(module.js: 703: 10)
    at startup(bootstrap_node.js: 193: 16)

  `const matches = fuzzysort.go(searchTerm, categories, fuzzyConfig);`

**Comment by farzher** [comment]
you'll have to first modify your data by joining the array into a string.

so, 
`categories.forEach(o => o.target = o.names.join(' '))`

then change the key to that string new
```diff
const fuzzyConfig = {
- key: 'names',
+ key: 'target',
  allowTypo: true,
  limit: 10
};
```

now you can search it `const matches = fuzzysort.go(searchTerm, categories, fuzzyConfig)`

**Comment by howlowck** [comment]
@farzher Simply joining the array of string into a string loses the significance of the separation.  

For the example above, "Perfectionist Tom" shouldn't return any result.  However because "Mr. Perfectionist" and "Tom Hanks of India" just happen to be next to each other, now will return back "Aamir Khan"

**Comment by farzher** [comment]
it's probably worth adding support for the key is array use case, but, does this work for you:

```javascript
var categories = [        
 {
    "category": "Akshay Kumar",
    "names": [
      "Akshay Kumar",
      "Khiladi",
      "Akki"
    ]
  },
  {
    "category": "Aamir Khan",
    "names": [
      "Aamir Khan",
      "A.K.",
      "Mr. Perfectionist",
      "Tom Hanks of India"
    ]
  }
]


var tmp_categories = []
categories.forEach(cat => {
  cat.names.forEach(name => {
    tmp_categories.push({category:cat, name:name})
  })
})

var results = fuzzysort.go('perfect tom', tmp_categories, {key:'name'})
results.forEach(r => r.obj = r.obj.category)
console.log(results)
```

**Comment by howlowck** [comment]
gotcha.. this would work but it dramatically increase the data size.

**Comment by vayyala** [comment]
> it's probably worth adding support for the key is array use case, but, does this work for you:

@farzher Is this still on the roadmap? I use a few keys where the value is an array of strings, so it would significantly increase the search array size for me. Thank you!

**Comment by farzher** [comment]
hmmmmmmmmmm, this is a weird hack but probably works fine?:

```js
var categories = [        
 {
    "category": "Akshay Kumar",
    "names": ["Akshay Kumar", "Khiladi", "Akki"]
  },
  {
    "category": "Aamir Khan",
    "names": ["Aamir Khan", "A.K.", "Mr. Perfectionist", "Tom Hanks of India"]
  }
]


var max_names_len = Math.max(...categories.map(c => c.names.length))
var keys = []; for(var i=0;i<max_names_len;i++) keys[i] = `names.${i}`

var results = fuzzysort.go('perfect tom', categories, {keys})
results.forEach(r => { // reformat results from keys results to key results
  r.sort((a,b) => (b?.score||-Infinity) - (a?.score||-Infinity))
  if(r[0]) {r.target = r[0].target; r.indexes = r[0].indexes}
})
console.log(results)
```

**Comment by razorness** [comment]
When you are working on this, would be nice to also cover the scenario having an array of objects behind a property like:
```ts
const categories = [        
 {
    "category": "Akshay Kumar",
    "names": [
      {id: 123. name: "Akshay Kumar"},
      {id: 124. name: "Khiladi"},
      {id: 125. name: "Akki"}
    ]
  },
  {
    "category": "Aamir Khan",
    "names": [
      {id: 126. name: "Aamir Khan"},
      {id: 127. name: "A.K."},
      {id: 128. name: "Mr. Perfectionist"}
      {id: 129. name: "Tom Hanks of India"}
    ]
  }
];
```

For now, your hack can also be applied for this scenario:

```ts
// TypeScript
const nameKeys: string[][] = [];
for (let i = 0, len = Math.max(...categories.map(c => c.names?.length || 0)); i < len; i++) {
    nameKeys.push([ 'names', String(i), 'name' ]);
}
const results = fuzzysort.go('perfect tom', categories, { keys: [ 'category', ...nameKeys ] }).map(s => s.obj);


```

**Comment by Leftium** [comment]
I found another method using object paths as keys
- like: `names.0`, `names.1`, ...
- nested property access should also work: `names.0.name`, `names.1.name`
- "Perfectionist Tom" is not matched like with concatenation

I left more details in another related issue: https://github.com/farzher/fuzzysort/issues/102#issuecomment-2499792373

Ah.. my solution is very similar to this comment which uses `['names', 0]` vs `names.0`: https://github.com/farzher/fuzzysort/issues/25#issuecomment-783245528
