### ISSUE TITLE
1.0.5 on npm is not the same as 1.0.5 on github

### ISSUE THREAD

**Issue by ljl** [farzher/fuzzysort#27]
Hi.

I recently started using this library, but got an error with `if(target === undefined) continue` since it did not match null values.

I was planning on making a PR, but noticed in the 1.0.5 release on github this has actually been fixed and replaced by `if(!target)`.

However, I use 1.0.5 fetched from NPM, and the source code i got from there uses triple equals undefined!

**Comment by farzher** [comment]
oops, i didn't realize 1.0.5 was the newest published version on npm.

i just published 1.1
