### ISSUE TITLE
Preparing objects for performance improvement

### ISSUE THREAD

**Issue by aguynamedben** [farzher/fuzzysort#28]
Hi, thanks for the time you spend on making this great library available to the public.

I'm indexing 100k objects. I really only want to search on obj.title. I'm only indexing objects so that I can also get obj.id back and do things with it. When I try to prepare **objects**:
```js
this._targets = records.map(record => fuzzysort.prepare(record));
```
An example record:
```js
{ _id: '09vlkj23029',
  _rev: '5-25acb1dd8a674d62bd39367dec7a3a9d',
  domain: 'mysite.com',
  source: 'myConnector',
  title: 'Jones Company - My Site',
  url: 'https://mysite.com/09vlkj23029' }
```

I get `TypeError: str.toLowerCase is not a function`, and I believe it's due to this line assuming targets are strings: https://github.com/farzher/fuzzysort/blob/master/fuzzysort.js#L511

It looks like a way to prepare an object could be built, but isn't yet implemented. Or maybe it was a regression. Any thoughts on this? Thanks again.

**Comment by farzher** [comment]
this._targets = records.map(record.titlePrepared => fuzzysort.prepare(record.title));

**Comment by farzher** [comment]
```diff
- this._targets = records.map(record => fuzzysort.prepare(record));
+ records.forEach(record => record.titlePrepared = fuzzysort.prepare(record.title));

fuzzysort.go('search', records, {key:'titlePrepared'})
```

**Comment by farzher** [comment]
`prepare` does nothing but take a string and return a weird obj, that can be searched as a string (just faster).

so when working with objects, you have to pick what prop you want to prepare, what to name the new prepared prop, then search your objects based on that key.

if you can think of a better api for preparing a string on an obj, let me know!

**Comment by aguynamedben** [comment]
Thanks! That worked great.
