### ISSUE TITLE
Feat discussion

### ISSUE THREAD

**Issue by Sunshine168** [farzher/fuzzysort#32]
hi,  i want  add additional usage about ```fuzzysort.highlight``` . Some time we want wrapper different style for the matches.
  Eg:
        ``` t and test  =>  <red>t</red>es<blue>t</bule>```
      so , and new feat  look like
    
![code](https://user-images.githubusercontent.com/15126380/38180185-23500a3c-365d-11e8-9df4-6f2ebe46e85e.png)

If i miss something ,  point me out is appreciate ！ 
And thx this wonderful lib

**Comment by farzher** [comment]
you can use `result.indexes` to highlight it yourself

```js
const result = fuzzysort.single('tt', 'test')
result.indexes // [0, 3]
```

**Comment by farzher** [comment]
This is the built-in highlight function, you can tweak it to do whatever you want

```js
function highlight(result, hOpen, hClose) {
  if(result === null) return null
  if(hOpen === undefined) hOpen = '<b>'
  if(hClose === undefined) hClose = '</b>'
  var highlighted = ''
  var indexesI = 0
  var opened = false
  var target = result.target
  var targetLen = target.length
  var matchesBest = result.indexes
  for(var i = 0; i < targetLen; ++i) { var char = target[i]
    if(matchesBest[indexesI] === i) {
      ++indexesI
      if(!opened) { opened = true
        highlighted += hOpen
      }

      if(indexesI === matchesBest.length) {
        highlighted += char + hClose + target.substr(i+1)
        break
      }
    } else {
      if(opened) { opened = false
        highlighted += hClose
      }
    }
    highlighted += char
  }

  return highlighted
}
```

**Comment by Sunshine168** [comment]
Oh thx ! i thought  it should be  tweak by myself !
