### ISSUE TITLE
Odd sort order

### ISSUE THREAD

**Issue by daverogers** [farzher/fuzzysort#34]
<img width="378" alt="screen shot 2018-04-23 at 10 20 54 am" src="https://user-images.githubusercontent.com/953524/39142682-31031956-46e0-11e8-9b90-1934fd8f2c12.png">

I'm curious why the first row is ahead of the following three, which seem like better matches in my view (as whole word matches). It looks like it should be under those three, where rows 5, 6, 7 are. Then the bottom result is really a best match, like 2, 3, 4; so it's placement is head-scratching as well.

**Comment by daverogers** [comment]
yeah i could see how longer names create more opportunities for poor matches. i would think that hitting on an entire word would be more favorable than two partials (or one word with three character matches being better than two words with one or two character matches).

**Comment by farzher** [comment]
i ran your example and the order is like this:

![image](https://user-images.githubusercontent.com/1005136/39400839-0acd59c0-4b06-11e8-852d-09805834f9a6.png)

which looks pretty good? why is yours different?

**Comment by daverogers** [comment]
Hmm, good question. I'll have to play with it.

**Comment by sam-zf** [comment]
I have a couple questions:

1. How did the examples differ?
2. Was this solved?
  - What was the solution?

**Comment by farzher** [comment]
> I have a couple questions:
> 
> 1. How did the examples differ?
> 2. Was this solved?
> 
> * What was the solution?

1. the examples are different because i had typos in my copy of them.
2. this was fixed in v2.0.0 https://github.com/farzher/fuzzysort/issues/97 by recognizing exact substring matches as special in the scoring system. even the longest string here would match above the non exact matches now
