### ISSUE TITLE
Credit

### ISSUE THREAD

**Issue by forrestthewoods** [farzher/fuzzysort#35]
It's pretty cool that you made a much faster, NPM version of this. It'd be nice if you could at least point people towards my original blog post.

https://blog.forrestthewoods.com/reverse-engineering-sublime-text-s-fuzzy-match-4cffeed33fdb

**Comment by farzher** [comment]
oh hi. this is independent of that. i used your demo page sample data, but that's it.

if you check the code, probably even the algorithm isn't similar.

btw, my js implementation is so good that it's the same speed (or faster?) than your c++ implementation.
you should translate this algo to c++, then compile to wasm, that'd be sick
