### ISSUE TITLE
Add a option for Latin extended characters map

### ISSUE THREAD

**Issue by vmasek** [farzher/fuzzysort#36]
It would be really helpful if there was an option to enable mapping all latin extended chars to basic ones. 
It would work similarly as when the strings are lowercased before matching. There are plenty helper methods for this like [latinize](https://github.com/dundalek/latinize/blob/master/latinize.js)

**Comment by farzher** [comment]
does this work for you? https://github.com/farzher/fuzzysort/issues/23#issuecomment-366492221

**Comment by vmasek** [comment]
I'll try that, didn't notice that issue

**Comment by vmasek** [comment]
Thank you, it had worked.
