### ISSUE TITLE
Search in files

### ISSUE THREAD

**Issue by Kuranes** [farzher/fuzzysort#38]
Is it intended for robust search in files ?

I'm trying to use it as a search in multiples files at once, but I'm getting bad search results. (exact correct word with bad scores (< 20000), multiple instance of word not  found, sometimes not found at all )

Is there some option I have to know about ?
(a "multiple results" per key perhaps ?)

Great work, thanks for sharing.

**Comment by Kuranes** [comment]
Code using fuzzysort is https://github.com/Kuranes/glslesideWebExtension/blob/master/src/ShaderEditor/powerSearch.js

Reproduction steps are not easy for now:
- install my chrome extension
https://chrome.google.com/webstore/detail/renderbugl%CE%B5-%CE%B2%E1%BF%86%CF%84%CE%B1/dejidhjkokejnkachmfldjbkjnhlcopj
- goto http://floooh.github.io/oryol-samples/wasm/Paclone.html
- open chrome devtools
- goto devtools tab "renderbuggle"
- select "search" lowerpane tab
- ctrl+p

some search
- "fragColor": 2 results, whereas there should be 6 results.
- ":highp": 3 results instead of 15

etc

**Comment by farzher** [comment]
i'll check it out.

i like how you're using prepareSlow even though that's not documented anywhere ^^

1 quick suggestion is that searching an entire file probably doesn't work well at all.
you should make each line its own search target (the score goes down a lot if the match isn't near the beginning)

**Comment by Kuranes** [comment]
Thanks.
That's what all those 'beginnings' do.

ok, well don't bother then.

Seems it jusy isn't a good fit for my case then, I'll do the full text search another way then.
(must be no penalty on long file or even long lines of code.)

I'll keep it for filenames, commands and perhaps variables names then. Makes much more sense that way.

Thanks for the quick and nice answer!
