### ISSUE TITLE
Move to ES5

### ISSUE THREAD

**Issue by bbenezech** [farzher/fuzzysort#4]
Please move to ES5 syntax

- replace arrow `=>` functions
- replace `const`
- replace `for ... of`
- replace string ` backticks

Usual webpack setups do not compile down node_module dependencies to es5.
It will make UglifyJS choke and won't work on some browsers.

If you want, you can provide both es6 and es5 through a package.json flag.

**Comment by mickdekkers** [comment]
Perhaps this project could use Babel instead, keeping the ES2015+ syntax while increasing compatibility with UglifyJS and older browsers.

**Comment by bbenezech** [comment]
Not worth it for a lib that is so perf oriented.
Unless there are some real advantages of let/const over var because of their scoping. But it does not seem evident so far.

https://jsperf.com/let-vs-var-loop

The other needed replacements aren't in hot paths, not worth checking IMO.

**Comment by farzher** [comment]
But I don't like ES5 :(

On a more serious note, removing `const` should have a negative impact on performance.

I'll try changing to ES5 and benching it.

**Comment by farzher** [comment]
Surprisingly, performance seems the same without const.
`for of` is the only thing I can't find a fast ES5 replacement for:

```js
for(const targetI of matchesBest) {
  if(lastTargetI !== targetI - 1) score += targetI
  lastTargetI = targetI
}
```

I tried replacing with this:

```js
for (var i = 0; i < searchLen; i++) {
  var targetI = matchesBest[i]
  if(lastTargetI !== targetI - 1) score += targetI
  lastTargetI = targetI
}
```

In an isolated benchmark, the 2nd one is twice as fast. But it's somehow slower during a full benchmark.
