### ISSUE TITLE
KeysResults obj property

### ISSUE THREAD

**Issue by vmasek** [farzher/fuzzysort#40]
Should the `obj: any` property be present in KeysResults type? https://github.com/farzher/fuzzysort/blob/master/index.d.ts#L38

It extends the KeyResult which has the `obj: T`, but in this case it gets overridden with `any`

**Comment by farzher** [comment]
man, i suck at typescript d.ts stuff

it shouldn't have the obj property at all, or the score property, only a total

**Comment by farzher** [comment]
^ obj and score need to exist there instead. and yeah it should be T instead of any
