### ISSUE TITLE
Highlighting indexes are generated only for the first match

### ISSUE THREAD

**Issue by kant01ne** [farzher/fuzzysort#47]
Hey! Thanks for all the hard work, I love the lib! So efficient!
I found a bug in the lib where only the first ocurence is taken into account to generate indexes:

Example:

```js
const results = fuzzysort.go('mr', ['Mr something mr']);
 => res.indexes = [0,1] // Should be [0,1,13,14]
```

Let me know if I can help.

**Comment by farzher** [comment]
working as intended. only shows the first occurrence, just like sublime text

![image](https://user-images.githubusercontent.com/1005136/46481233-f43bad00-c7c0-11e8-8948-b4a2464d049c.png)
