### ISSUE TITLE
scoreFn always receives [null,null] as an input?

### ISSUE THREAD

**Issue by lets-do-this-challenge** [farzher/fuzzysort#48]
Hi there! Does anyone have an idea why my scoreFn doesn't work? Thanks all!

```
let options = {
        limit: 100,
        allowTypo: false,
        threshold: -10000,
        keys: ["name1","name2"],
        scoreFn: function(a) {console.log(JSON.stringify(a,null,2)); return a[0].score;} //function seems to be broken -- scoreFn input always receives [null,null]
      };
let results = fuzzysort.go("a", [{"name1":"ab","name2":"k"},{"name1":"b","name2":"k"}], options);
```

**Comment by farzher** [comment]
wtf is that print? lol. just do this so you can more clearly see what's happening

```scoreFn: function(a) {console.log(a)}```

a[0].score is crashing when a[0] is null

**Comment by lets-do-this-challenge** [comment]
@farzher ah sorry! `JSON.stringify(someObject,null,2))` prints a beautified version of any object to the screen

`console.log(a)` gives the same:  [null,null]

**Comment by lets-do-this-challenge** [comment]
@farzher Still need help. I don't understand why `a === [null,null]`.  Is it normal?

**Comment by lets-do-this-challenge** [comment]
Are you able to run my code on your side and make the `scoreFn` change the score of the results?

**Comment by farzher** [comment]
like i said, `a[0].score` is crashing your code when `a[0]` is null.

![image](https://user-images.githubusercontent.com/1005136/47328255-65db7e00-d63e-11e8-9221-ecaa421881d3.png)

i just changed `a[0].score` to `a[0]?a[0].score:-10000`

**Comment by lets-do-this-challenge** [comment]
@farzher   ok, but why is `a[0]` null? it doesn't have a score?

**Comment by farzher** [comment]
`null` is normal, it means there's no match.
those object are match results.

**Comment by lets-do-this-challenge** [comment]
The "a" search doesn't match "ab"?

**Comment by lets-do-this-challenge** [comment]
I think I discovered something.

First try, I search "ab" and the first object has a "name1" of "ab". It doesn't match.

```
const fuzzysort = require('fuzzysort');
let options = {
    limit: 100,
    allowTypo: false,
    threshold: -10000,
    keys: ["name1","name2"],
    scoreFn: function(a) {console.log(JSON.stringify(a,null,2)); return a[0].score;} //function seems to be broken -- scoreFn input always receives [null,null]
};
let results = fuzzysort.go("ab", [{"name1":"ab","name2":"k"},{"name1":"dsa","name2":"k"}], options);
```

Second try, I search "ab" and both first object have a "name1" of "ab". Now, it matches.

```
const fuzzysort = require('fuzzysort');
let options = {
    limit: 100,
    allowTypo: false,
    threshold: -10000,
    keys: ["name1","name2"],
    scoreFn: function(a) {console.log(JSON.stringify(a,null,2)); return a[0].score;} //function seems to be broken -- scoreFn input always receives [null,null]
};
let results = fuzzysort.go("ab", [{"name1":"ab","name2":"k"},{"name1":"ab","name2":"k"}], options);
```
I also tried with my full database (a .csv file). And it's sometimes doing crazy things like that when having "scoreFn" and/or multiple keys. However, I cannot pinpoint the source of the problem.

**Comment by lets-do-this-challenge** [comment]
Ok, sorry, I get it sorry, the `scoreFn` is called separately for every object provided.  The keys are replaced by `null` when the search doesn't match.
