### ISSUE TITLE
Rank consecutive characters higher regardless of position in string

### ISSUE THREAD

**Issue by scelera** [farzher/fuzzysort#49]
First off this is a great library, thank you for all the work you put into this.  Works so much faster and is more intuitive than anything else I've tried. 

I've noticed that when only searching using a few characters, say 3, it will rank matches higher based on their position in the searched string rather than if the characters are consecutive.  

Example:
Search parameter = pin
Search string 1= porting in
Search string 2 = account pin
Result = 
1. **p**orting **in**
2.  account **pin**

I would've expected it to show the reverse
1.  account **pin**
2. **p**orting **in**

That seems much more relevant to me and maybe there is a way to do this and I just haven't figured it out so any feedback would be appreciated.

As a side note, not sure why **p**orting **in** would highlight as indicated instead of showing as **p**ort**in**g in.

**Comment by farzher** [comment]
it's a delicate balance.

there's 2 different reasons you might want to search.
1. search: for all things matching `pin`, in which case you want `account pin`
2. lookup: something i already know exists ex `porting in` the "issue" you're having is what allows for this.

the scores there are so similar that if you add one more character to `porting in` ex `portingg in`, it swaps positions

if i search `fff` then `DiffFilesCommandlet.h` is a good match.
if i want to lookup `FontFileImportFactory.h` by typing `fff` then `DiffFilesCommandlet.h` is a bad match

**Comment by scelera** [comment]
That makes sense, is there anyway to 'toggle' the behavior?

**Comment by farzher** [comment]
no. it just works the same way as sublime text

![image](https://user-images.githubusercontent.com/1005136/47750514-f0873300-dc65-11e8-82ea-c35a239ec236.png)

**Comment by timendez** [comment]
Is there a way to weight it slightly higher if it's a consecutive match preceded by a space? I'm no expert so there might be a case where this isn't desired, but I can't think of any off the top of my head.
