### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by bbenezech** [farzher/fuzzysort#5]
You can add some typings:

`./index.d.ts` at the root
```typescript
declare module "fuzzysort" {
  interface Result {
    score: number;
    highlighted: string;
    _matchesBest: number[];
    _matchesSimple: number[];
    _target: string;
    _targetLower: string;
  }

  interface Results {
    [index: number]: Result | undefined;
    thresholdCount: number;
    total: number;
  }

  const fuzzysort: {
    noMatchLimit: number; // If there's no match for a span this long, give up (lower is faster for long search targets)
    highlightMatches: boolean; // Turn this off if you don't care about `highlighted` (faster)
    highlightOpen: string;
    highlightClose: string;
    threshold: number | null; // Don't return matches worse than this (lower is faster) (irrelevant for `single`)
    limit: number | null; // Don't return more results than this (faster if `highlightMatches` is on) (irrelevant for `single`)
    allowTypo: boolean; // Allwos a snigle transpoes in yuor serach (faster when off)
    single(search: string, target: string): Result | null;
    go(search: string, targets: string[]): Results;
    goAsync(search: string, targets: string[]): Promise<Results>;
  };

  export = fuzzysort;
}
```
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by farzher** [comment]
Thanks for the example file. I'll push this after I figure out how to get typescript working so that I can test it... might be a while.

**Comment by GrzegorzWidla** [comment]
@farzher it's just a definition file that will give those who use TypeScript autocompletion on fuzzysort in their IDE of choice. I can also confirm that it's well written type definition that works perfectly.

As you can see @bbenezech has described all configuration options and functions fuzzysort offers. If you look at `single`, `go` and `goAsync` those are defined as functions that accept some parameters and then return `Result` or `Results` object that are defined as interfaces above.

If you want to learn TypeScript though, consider this book as it's probably the most comprehensive source: https://www.gitbook.com/book/basarat/typescript/details

**Comment by farzher** [comment]
I want to edit it a bit and add "docblock" comments.

Is it possible to have typescript detect this definition automatically from within the node_modules folder? I have to add `/// <reference types="fuzzysort" />` to the top of my test typescript to get it to work.

**Comment by GrzegorzWidla** [comment]
It'll do that if you import a module into your code base. If the npm published module contains definition files it'll work automatically without any references.

`import * as fuzzysort from 'fuzzysort'`

When module doesn't ship with definition files itself you check if there are typings for it from DefinitelyTyped - open source project where people collaborate on `d.ts` files for popular libraries. You can install those via npm, e.g. `npm install @types/jquery --save-dev`.

When you create type definition for specific library you declare and export module of the same name in it. In short, it doesn't matter where your definitions come from - as long as they are discoverable to the compiler.

By default compiler looks in imported module's directory and in `node_modules/@types`. You can expand that with any directory or specific files via `tsconfig.json` file, for example if you've written custom declarations: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types

jQuery type definitions are very comprehensive, including documentation, so you can check them out for any inspiration: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jquery/index.d.ts

**Comment by farzher** [comment]
Cool, thanks for the overview. Idk why it wasn't finding the definition automatically before. It's working fine now.

Some of those jQuery types are insane!

**Comment by Lucassith** [comment]
Are those .d.ts definitions correct? It does not allow to import Results interface as a return type and use it to type the variable.

**Comment by farzher** [comment]
oops, you're right. the types aren't exported.
i'll update it (when i figure out how).
