### ISSUE TITLE
obj property is always null

### ISSUE THREAD

**Issue by dbize** [farzher/fuzzysort#52]
Hi, I am trying **this search**

const fuzzysortOptions = {
          limit: 50, // don't return more results than you need!
          allowTypo: false, // if you don't care about allowing typos
          threshold: -10000, // don't return bad results
          keys: ["username"]
}

fuzzysort.go(
     'ssa', 
     [ 
        { code: 'USR-20181206042453262-0QqTbZRi', username: 'ssampson0' }, 
        { code: 'USR-20181206042453311-GhgVv1j7', username: 'rfitzer1' } 
     ], 
     fuzzysortOptions
)

And **getting this result**

[ [ { "target": "ssampson0", "_targetLowerCodes": [ 115, 115, 97, 109, 112, 115, 111, 110, 48 ], "_nextBeginningIndexes": [ 9, 9, 9, 9, 9, 9, 9, 9, 9 ], "score": -6, "indexes": [ 0, 1, 2 ], "obj": null } ] ]

However, **obj is always null.** 
If you find this is not an issue, Can you advice to locate the items in the targets arrays?

**Comment by farzher** [comment]
obj isn't null for me. 

go here and run it in the console https://rawgit.com/farzher/fuzzysort/master/test.html

**Comment by yuvi1947** [comment]
@dbize can you post the full code here ? Even i faced the same situtation but then i realized it is more of a misunderstanding. You can understand better if you log the complete result to better understand the structure of the output.
```
let  result  = fuzzysort.go('ssa',[
{ code: 'USR-20181206042453262-0QqTbZRi', username:'ssampson0' },
{ code: 'USR-20181206042453311-GhgVv1j7', username: 'rfitzer1' }],
fuzzysortOptions);

console.log(JSON.stringify(result));
```

**Comment by calumks** [comment]
I faced the same issue using fuzzysort in a react native app.

Even though console.log() show's obj as null, this isn't the case and you should still be able to access the object. 

I'm not sure why this happens, but If you use goAsync, you may find it loses the obj reference after you resolve the promise. 
`results = results.map(r => Object.assign({}, r));` should solve the issue but it's obviously not ideal.

**Comment by deepsidh9** [comment]
> I faced the same issue using fuzzysort in a react native app.
> 
> Even though console.log() shows obj as null, this isn't the case and you should still be able to access the object.
> 
> I'm not sure why this happens, but If you use goAsync, you may find it loses the obj reference after you resolve the promise.
> `results = results.map(r => Object.assign({}, r));` should solve the issue but it's obviously not ideal.

I tried to access the "obj" object while using fuzzysort in my react native app too but was unable to access it. 

My way of searching : 

`let results = fuzzysort.go(text, allDocuments, {
        keys: ["file_name", "description","tagsString"],
      })
`

while my allDocuments is an `Array` with 4 objects like :

` Object {
    "description": "Pinterest screenshot",
    "favorites": Array [],
    "file_name": "Great art",
    "id": "hAohaBdtRJSWgH1PUJyG",
    "local_file_path": "filePathHere",
    "local_image_url": "imageurlhere",
    "main_category": "family-photos",
    "network_url": "networkUrlHere",
    "tags": Array [
      "Girl",
      "Yoga",
      "Art",
    ],
    "tagsString": "Girl Yoga Art",
    "timestamp": 1592829546.338198,
    "upload_date": "June 22, 2020",
  }
`
I tried the `goAsync` way but that too didn't resolve it. 

I get results for "Girl" along the lines of : 

`Array [
  Array [
    null,
    null,
    Object {
      "_nextBeginningIndexes": Array [
        4,
        4,
        4,
        4,
        5,
        9,
        9,
        9,
        9,
        10,
        13,
        13,
        13,
      ],
      "_targetLowerCodes": Array [
        103,
        105,
        114,
        108,
        32,
        121,
        111,
        103,
        97,
        32,
        97,
        114,
        116,
      ],
      "indexes": Array [
        0,
        1,
        2,
        3,
      ],
      "obj": null,
      "score": -9,
      "target": "Girl Yoga Art",
    },
  ],
]`

**Comment by JackNgWeiMing** [comment]
same problem as @deepsidh9  ,using react-native@0.62 with typescript@4.13

**Comment by farzher** [comment]
ah i see. this is definitely confusing, but for performance reasons, when using `keys`, obj is infact always null.

your obj is on the KeysResult itself.

```js
const results = fuzzysort.go('yo', [{name:'yo mama'}], {keys:['name','name']})
for(const result of results) {
  console.log(result[0]/*info about my first key*/.obj) // always null
  console.log(result.obj) // here's your object
}
```
