### ISSUE TITLE
How to give higher priority to certain entries over others?

### ISSUE THREAD

**Issue by mubaris1** [farzher/fuzzysort#53]
I'm performing search on an array which looks like following: 
       `[
         {
		"city" : "Anaa",
		"country" : "French Polynesia",
		"code" : "AAA"
	},
	{
		"city" : "Al Arish",
		"country" : "Egypt",
		"code" : "AAC"
	},
         ...]`
and so on. 
I'm applying a search on 'city' and 'code' fields of the array. So, when the user searches for 'b',   he will be shown all results that have b in their 'city' or 'code'.
My question is, how do I give higher priority to results from a particular country? In other words, I want the result to assign higher priority to Indian cities. How can I go about that?

**Comment by farzher** [comment]
```javascript
var objects = [ { "city" : "Anaa", "country" : "French Polynesia", "code" : "AAA" }, { "city" : "Al Arish", "country" : "Egypt", "code" : "AAC" }, { "city" : "Mumbai", "country" : "India", "code" : "IND" }]
var results = fuzzysort.go('b', objects, {
  keys: ['city', 'code'],
  scoreFn: (keysResult) => {
    var cityResult = keysResult[0]
    var codeResult = keysResult[1]
    var score = Math.max(cityResult?cityResult.score:-Infinity, codeResult?codeResult.score:-Infinity)
    if(keysResult.obj.country === 'India') score += 10000
    return score
  }
})

console.log(results)
```

**Comment by mubaris1** [comment]
Now this works really well! Thanks!
