### ISSUE TITLE
Accents

### ISSUE THREAD

**Issue by Mushr0000m** [farzher/fuzzysort#55]
Is there a way to make the plugin handle accent as char without accent ? For example in your demo on Steam games, if you enter `café ` you have the game `café  society`, but with the search `cafe` it doesn't show up.

**Comment by farzher** [comment]
no. but you can just manually normalize the search/targets to solve that https://github.com/farzher/fuzzysort/issues/23#issuecomment-366492221

**Comment by Mushr0000m** [comment]
And will it still be able to highlight matches ?

**Comment by farzher** [comment]
hmm. you can highlight using this hack `fuzzysort.highlight({...r, target:r.obj.original}))`. i'll add it to the example code i linked

**Comment by farzher** [comment]
this is fixed in v3.1.0

**Comment by Amerlander** [comment]
Thank you for the update! It works quite well overall.

However, I've noticed that some special characters aren't matched as expected for my specific use cases, which might be somewhat niche:

- **Visually similar characters**: For example, `ø` is commonly used in Norway, but users from other countries might just type `o`, as it's the closest match on a standard ISO keyboard. Similarly, `ｅ` might be typed as `e`, and vowel sounds like `ⱥ` as `a` or `ɛ` as `e`.
- **Mathematical symbols**: Characters such as `ℯ` for `e` and `ƒ` for `f` aren't currently being matched.
- **Characters with similar meanings**:
  - For example, symbols like `+` and `&` could be considered interchangeable in some contexts.
  - `\` and `/` are interchangeable in some cases (path windows, vs unix)
  - Quotes could be typed in many ways: `'`, `"`, `'`, `»`, `«`, `„`, `“` and \` .
  - A elispsis `…` would be considered to be matched by a dot `.`.
  - Coming to decimals, some users would type comma `,` as floating point, in these cases it should match a dot `.`.

These might be edge cases, so I do not expect them to be addressed. I just mention them to have the limitations noted in this issue. Thanks again for the great work!

**Comment by farzher** [comment]
@Amerlander this is a good comment, i'll probably address this... at some point.

it's interesting that `ø` isn't converted to `o` by `'ø'.normalize('NFD')`

where did you get that list of character mappings in your pull request? is it exhaustive?

**Comment by Amerlander** [comment]
@farzher no, I dont think it is exhaustive. It ist handmade for my own needs.

Since it is still based on an old version of fuzzysort I closed the PR, so the latest changes are not present there. I just pushed them and you can view them in my fork. But its just the addition of a few more quote types: https://github.com/Amerlander/fuzzysort/blob/1994aec2ae4a613584e2eed06ed7532163966cd6/fuzzysort.js#L374
