### ISSUE TITLE
Is it possible to have "both ways" sort?

### ISSUE THREAD

**Issue by kevinmamaqi** [farzher/fuzzysort#58]
Hi,

Is it possible to make the search go both ways? -  When you start with the final word of the search, the algorithm stops: https://streamable.com/r4wd6

**Comment by farzher** [comment]
nope.

the algo is probably fast enough for you to do multiple searches and combine the results though. you could make a 2nd list of targets with the words reversed.

but i don't have a code sample for this, and it's not trivial.

maybe this is helpful, but it's not exactly what you want https://github.com/farzher/fuzzysort/issues/19#issuecomment-353737466

**Comment by farzher** [comment]
i came up with this to solve this and similar issues

```js
const go = (search, targets, options) => {
  if(!Array.isArray(search)) return fuzzysort.go(search, targets, options)
  return search
    .map(s => fuzzysort.go(s, targets, options)
    .map(r => { return {...r} }))
    .flat()
    .sort((a,b) => a.target<b.target?-1:1)
    .filter((result, i, results) => !i || result.target !== results[i-1].target)
}
```

with this, search can be an array of searches, and the results are combined. in your case you'd just do this
```js
var results = go([search, search.split(' ').reverse().join(' ')], targets, options)
```
