### ISSUE TITLE
Documentation on score

### ISSUE THREAD

**Issue by wmonecke** [farzher/fuzzysort#61]
It seems that score can be as low as it wants to and I thought the score would be from 0 to -100. So is there a way to set a lower limit? If the score is able to go to -♾ then it makes no sense.

**Comment by farzher** [comment]
a score of 0 is a perfect match
each imperfection subtracts points (it can go to -♾)
a single fatal mistake means no match at all

it's just like sublime text, what doesn't make sense?

referencing https://github.com/farzher/fuzzysort/issues/19#issuecomment-353707884 to link the issues
