### ISSUE TITLE
How should I Handle ampersands (&)?

### ISSUE THREAD

**Issue by MarcelloTheArcane** [farzher/fuzzysort#63]
I'm searching titles, which might be something like `Fish & Chips`. What would be the best way of allowing search of `Fish & Chips` and `Fish and Chips`?

I suppose mutating some hidden name property that it _actually_ searches to be `Fish &and Chips` so it matches either, but I need to save and view it with the ampersand.

**Comment by farzher** [comment]
search for both `&` and `and` and merge results https://github.com/farzher/fuzzysort/issues/58#issuecomment-602157414


in your case:
```js
var results = go([search, search.replace(/\band\b/g, '&')], targets, options)
```
