### ISSUE TITLE
fuzzysort.single() options commented out?

### ISSUE THREAD

**Issue by mateogianolio** [farzher/fuzzysort#64]
https://github.com/farzher/fuzzysort/blob/c6604993ac51bfe4de8e82c0a4d9b0c6e1794682/fuzzysort.js#L37-L41

Is there any specific reason this code is commented out? I would like to set `threshold`. The only option accepted by `fuzzysort.single` right now is `allowTypo`.

**Comment by farzher** [comment]
no options is better performance. if you want a threshold just check the score

```js
var result = fuzzysort.single(s, t); if(result && result.score < mythreshold) result = null
console.log(result)
```

**Comment by mateogianolio** [comment]
Makes sense! Just thought it was an oversight since it was commented out :) Closing...
