### ISSUE TITLE
Search for "i" in Jungheinrich returns match Junghe*i*nri*ch* instead of Jungheinr*ich*

### ISSUE THREAD

**Issue by jnachtigall** [farzher/fuzzysort#65]
As the title says. If I search for "i" in Jungheinrich then I would expect the match to be Jungheinr*ich* and not Junghe*i*nri*ch*. Because it is a whole substring (syllable) and not separated characters.

**Comment by farzher** [comment]
sorry but this search doesn't understand German, lol. (or English for that matter)

**Comment by jnachtigall** [comment]
The thing is that the score seems kinda wrong here.

**Comment by ajitid** [comment]
> The thing is that the score seems kinda wrong here.

You are not wrong @jnachtigall. Here is the same word searched in Sublime Merge.

![sublfuzzysort](https://user-images.githubusercontent.com/26769888/127686099-322ff28a-9110-4a7d-a72d-211972775f3f.gif)

However this library gives Sublime-like search, and doesn't promises to exactly match with Sublime. So in that sense, I won't say the scoring is wrong here, just that it doesn't aligns with you would have expected.

Though I secretly wish @farzher disagrees with me and sees it as a bug. 😄

**Comment by farzher** [comment]
ah, i'm dumb, i understand the problem now.

i think this was done on purpose, as a tradeoff for better performance.

if it's only a difference between two bad matches, it doesn't try to optimize it. if it's the difference between a bad match vs a good match though, it will find the good match. ex: if your target was Jungheinr.ich it would match Jungheinr.`ich`

i'd fix this if i could figure out how to do it without impacting performance

**Comment by farzher** [comment]
marking this as wontfix for performance reasons until there's examples of it being a problem
