### ISSUE TITLE
Option to expose match ranges instead of adding highlight tags

### ISSUE THREAD

**Issue by mickdekkers** [farzher/fuzzysort#7]
People may want to use this package outside of a browser setting, where HTML tags don't do much.
It would be great if it exposed the match indices so they could be used with e.g. [`String.prototype.slice`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/slice).

**Comment by farzher** [comment]
```js
fuzzysort.single('ts', 'test')._matchesBest // [0, 2]
```

I'll add to the documentation when it's more finalized.

**Comment by farzher** [comment]
I added it to the documentation and renamed it to `indexes`.
