### ISSUE TITLE
Works great for one word, but not multiple words in different order.

### ISSUE THREAD

**Issue by Maarondesigns** [farzher/fuzzysort#73]
In my example, a DB includes "Salt, Table" as an entry. "salt" and "salt table" match fine, however "table salt" returns no matches at all. The words being in a different order could be a very common scenario for many things, not just this particular DB which is a list of cooking ingredients. Otherwise it seems to work great, thanks for the library. I installed it and got it working in less than 5 minutes.

**Comment by farzher** [comment]
this was an oversight

does #58 solve your problem

**Comment by Maarondesigns** [comment]
Yep that solves it, but I am actually just splitting the string and merging the results of each word. Works so far without a lot of searches containing prepositions.
