### ISSUE TITLE
Possible to prioritize long string containing exact matched word?

### ISSUE THREAD

**Issue by Maarondesigns** [farzher/fuzzysort#74]
In my example, the search word is "salt".

The sorted results are:
1. "Salt, table", -7
2. "Salmon, atlantic, wild, cooked", -54
3. "Cabbage, red, cooked, boiled, drained, with salt", -88
4. "Brussels sprouts, cooked, boiled, drained, without salt", -102
5. "Cabbage, chinese (pak-choi), cooked, boiled, drained, with salt", -118

I am assuming #2 ranked higher because the other strings are longer and therefore required more deletions to match, however is there a way to prioritize a string containing an exact match? I think (at least in this case) #2 should have a lower score since the letters making up "salt" aren't even contained in the same word, whereas several other results contain the entire matched word.

**Comment by farzher** [comment]
that's mostly a weird side effect of allowing typos. it's matching well against `*S*almon, *atl*antic, wild, cooked`

are you fine with just setting `allowTypo: false` ?

**Comment by Maarondesigns** [comment]
I will continue testing with that set to false and let you know, thanks!
