### ISSUE TITLE
How can I use it with large database?

### ISSUE THREAD

**Issue by gosforth** [farzher/fuzzysort#75]
I search for some algorithm that will find similar products; for instance I have 'red pen' so find me similar products. The problem is that database contains 120 thousands of products so I cannot select all article description into javascript object (even SQL will not allow me to do that - characters limit).
Any suggestion?
Anyway; you say this library will give me better result that 'fuzzyset'?

Regards

**Comment by phpmydev** [comment]
Look into elasticesearch - we are using it in our application.  [https://www.elastic.co](https://www.elastic.co)

**Comment by gosforth** [comment]
Finally I managed it with Neo4j. Works damn fast and gives really great result.
I tried Elastic and I do not recommend - really poor results.

**Comment by farzher** [comment]
yea, you can't use this to search your database, you have to use your database's built in search functionality :(

(unless you wanna load your entire database into ram)
