### ISSUE TITLE
Negative score makes little sense

### ISSUE THREAD

**Issue by wmonecke** [farzher/fuzzysort#78]
I am quite confused as to why the score is negative and it says higher is better in the documentation.
If something does not match at all I get a score of 0 in my tests. If it does match I get -4. 
How is it then that 0 is better than -4 (higher being better)?

Sorry if this is a silly question I just have thought about this for a while and cant understand it.
Thanks for the amazing library!

**Comment by farzher** [comment]
no match isn't 0 it's `null`
a perfect match is `0`
any issues subtract from the perfect score of 0

**Comment by wmonecke** [comment]
Oh ok this is my bad then because I initialized a score variable as 0 and didn't notice `null` was returned on no matches.
Thank you for your time!
