### ISSUE TITLE
Possible to use as a solution to omitted letters?

### ISSUE THREAD

**Issue by phpmydev** [farzher/fuzzysort#79]
I apologize for using the issues as a place to ask my question, but I don't know of any other way to reach you.
My use case is such that if someone types entrprse I need it to match enterprise.  Is this possible with fuzzysort?
I appreciate your response!

**Comment by farzher** [comment]
that's a match. just not a very good one. it's possibly getting blocked by your `threshold`?

![image](https://user-images.githubusercontent.com/1005136/109459057-0969a400-7a2c-11eb-89d6-4dc5d07e0e5e.png)
