### ISSUE TITLE
Exponential backtracking hangs browser

### ISSUE THREAD

**Issue by gyk** [farzher/fuzzysort#80]
The computation of `matchesStrict` is susceptible to [catastrophic backtracking](https://www.regular-expressions.info/catastrophic.html). For example, the following code makes the for-loop run more than 1 billion times:

```js
let s = 'a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a xb'
fuzzysort.single('aaaaaaaaaaab', s, { allowTypo: false });
```

This is a contrived example, but in some real-world scenarios, longer text and search term also freezes the browser due to the same reason.

**Comment by magne4000** [comment]
We have this exact issue with real world data indeed. Do you have any ideas on how to avoid the issue?

**Comment by gyk** [comment]
@magne4000 I don't know, but I think the library is not really designed for searching long text, so a big collection of variable names, file names or titles should be OK but a few long paragraphs of text probably not.

**Comment by MatthD** [comment]
We did a fix to prevent those kind of Infinite loop , You can take a look at our fork commit https://github.com/getstation/fuzzysort/commit/003352b1381f76893a15aa4ce1fe4f0bac9d4caf

**Comment by AJamesPhillips** [comment]
@MatthD thanks for linking to your code.  I tried it out with the example given at the top and it doesn't seem to help unfortunately.

**Comment by AJamesPhillips** [comment]
@MatthD thanks for linking to your code.  I tried it out with the example given at the top and it doesn't seem to help unfortunately.  I see @gyk moved to use FlexSearch: https://github.com/logseq/logseq/pull/1302 , have you tired that?  It doesn't seem to have fuzzy search in it.

**Comment by AJamesPhillips** [comment]
[3rd party NPM package](https://www.npmjs.com/package/diff-match-patch) of Google's diff-match-patch might be a better option.  I just tested it using [their demo match tool](https://neil.fraser.name/software/diff_match_patch/demos/match.html) found from [their github page](https://github.com/google/diff-match-patch) and it worked fine.

**Comment by farzher** [comment]
anyone know if there's even a solution for this?

i'll probably just make it give up and return a less accurate match if it's taking too long
