### ISSUE TITLE
can this return an array similar to original

### ISSUE THREAD

**Issue by craigcosmo** [farzher/fuzzysort#86]
can this return an array similar to original ? but change in item order.

right now it returns something like `// [{score:-18, obj:{file:'MeshRenderer.cpp'}}, {score:-6009, obj:{file:'Monitor.cpp'}}]`

which is inconvenient, take a lot more mapping to use it as search drop like google search.

**Comment by Myrmod** [comment]
I am using it like this:

```js
import fuzzysort from 'fuzzysort'

async function searchPosts(searchValue: string, posts: { title: string, slug: string}) {
  const results = await fuzzysort.goAsync(searchValue, posts, {
    keys: ['title'],
  })

  return results.map(res => res.obj)
}
```

Works perfectly fine on my [website](https://myrmod.de/) where I am searchingthrough posts and pages of a headless cms. I might add a blogpost for this later.

**Comment by z0xyz** [comment]
Didn't want to fiddle with the source code nor scour through the forks for my desired feature , so had to resort to extra overhead of a wrapper function
```
function neoGo(string , list){
    let matchedItems = fuzzysort.go(string , list)
    let neoMatchedItems = []
    for (let i=0 ; i<matchedItems.length ; i++) {
        neoMatchedItems.push(Object.values(matchedItems[i])[0])
    }
    return (neoMatchedItems)
}
```

**Comment by farzher** [comment]
maybe i don't understand but this doesn't seem like an issue?
