### ISSUE TITLE
Search for an exact word

### ISSUE THREAD

**Issue by flamewave000** [farzher/fuzzysort#87]
It would be nice if one could surround a word or portion of a search with double quotes to perform an "exact" search. This wouldn't necessarily care about capitalization, and could also allow some misspelling. The idea would be that only results in which all of those characters are connected together would return. As an example, the phrase `Hell ought to be hot` would return a high score if I search for the word `hello` as `*Hell o*ught` would match. By surrounding the search in quotes, the phrase would not match as the letters are not directly connected. This would help users to eliminate many false-positives.

**Comment by farzher** [comment]
simply filter the results to only contain what you want.

here, `fuzzysort.mygo` will require parts of the search in quotes to be exact matches

```javascript

fuzzysort.mygo = (search, targets, options) => {
  let requiredmatches = []
  search = search.replace(/"(.*?)"/g, function(match, contents) {
    requiredmatches.push(contents)
    return contents
  })
  let results = fuzzysort.go(search, targets)
  return results.filter(result => {
    return requiredmatches.every(required => result.target.match(required))
  })
}

fuzzysort.mygo('"Hello"', ['Hell ought to be hot', 'Hello World!']) // 'Hello World!'
fuzzysort.mygo('"Hello" "World"', ['Hello Wo rld', 'Hello Mr. World!', 'Hello World!']) // ['Hello World!', 'Hello Mr. World']

```
