### ISSUE TITLE
Highlighting API

### ISSUE THREAD

**Issue by bbenezech** [farzher/fuzzysort#9]
I don't get the highlight function. Are you sure you want to maintain that? Outputing HTML sounds a bit off-topic.

If I were you, I would simply expose `matchesBest` and extract the highlighting function to a code sample linked in the readme.
You've thought about the case sensitiveness, but what about diacritics? With double chars diacritics, it can get complicated quickly.

You can let the user prepare the data and the searched value (toLowerCase/Diacritics) and simply output matches (do the thing you do best).

**Comment by farzher** [comment]
I think it's too inconvenient to not highlight; most people will want it (when would you not want it?)

When using the lib, I don't want to also paste highlighting nonsense into my codebase.

HTML seems on-topic enough for a javascript library. It lets you wrap matches with anything though, not just html `fuzzysort.highlightOpen = fuzzysort.highlightClose = '*'`

I don't think there's anything to maintain, it seems to work fine, even with weird characters

**Comment by bbenezech** [comment]
>> when would you not want it?

If you want to deal with highlighting, you need to deal with diacritics. Even some english words have them.

Users will most likely type `cafe`, when looking for `café`.

And it is not trivial: `Œuf` (egg) is 3 chars long, `oeuf` is 4 chars long, so matches index won't match.

**Comment by farzher** [comment]
Oh, I see. In those cases we don't even return matches. `e != é`

The user has to translate the target themselves, and highlight themselves, which they can do.

Is there anything wrong with that?
