### ISSUE TITLE
Trying to see the rationale 

### ISSUE THREAD

**Issue by halukkaramete** [farzher/fuzzysort#97]
You have an outstanding library.  Im curious to know if there is a rationale in the following scenario.

Please take a look at this screenshot. 

<img width="534" alt="Screen Shot 2022-04-05 at 6 47 31 AM" src="https://user-images.githubusercontent.com/4029735/161675372-8188f4e3-1462-4bbe-ad46-8c70198080b0.png">

Why do you think the much closer matches ( entries containing "audio" word ) are all beaten by a not-so-close match? 
What property or the logic in your algorithm is causing the following 4 entries to score better? 

<img width="448" alt="Screen Shot 2022-04-05 at 6 55 57 AM" src="https://user-images.githubusercontent.com/4029735/161676067-6399af99-db96-4220-8d50-de865b54572e.png">

I'm asking this only because there may be merits in doing so, that I fail to see.  And If there are ways to tell the engine to use a different algorithm to value what I'm suggesting more..  

It seems to me that if your highlights end up turning almost the entire word into red word ( as in these examples below ) 

<img width="174" alt="Screen Shot 2022-04-05 at 7 01 17 AM" src="https://user-images.githubusercontent.com/4029735/161676419-1de91a2e-430b-4ba6-9e5d-6fea3fe89ea9.png">

should definitely beat those that are far from that "redness". 

<img width="409" alt="Screen Shot 2022-04-05 at 7 02 13 AM" src="https://user-images.githubusercontent.com/4029735/161676512-fc418f26-bdc9-4332-9661-2478a1ada667.png">

What we perceive as a human beings should also be taught to the algorithm by comparing things like the density of the highlights, (the closeness of the red letters which is a function of the number of consecutive red letters). Simply put, if we compare the consecutive red-letter counts to the overall entry word count, the more dense highlights should rise to the top.  

I'd like to hear your valuable opinions on this.

**Comment by farzher** [comment]
this is very much intended

the scoring algo has the concept of strict matches vs bad matches
`A`u`dio` is considered a bad match because `d` isn't a BeginningCharacter
`A`pp`D`ata`IO` is considered a strict match because of the casing

although your example does actually seem like an issue. because those strict match results are requiring a transpose from `options.allowTypo`. maybe the typo penalty needs to be more severe. if you set allowTypo to false you'll get the results you expect

**Comment by TheHolyRoger** [comment]
@farzher would be great to have your input here please: https://github.com/home-assistant/frontend/discussions/12590

**Comment by farzher** [comment]
fixed in v2.0.0

**Comment by vincerubinetti** [comment]
It seems `allowTypo` was removed in v2 a while ago.

I'd like to use this library, but it doesn't protect against typos or insertions, e.g. go to [the demo](https://rawgit.com/farzher/fuzzysort/master/test/test.html) and try "fuzxysort" or "fuzzzysort".
