### ISSUE TITLE
spaces affect fuzzysort.single() score

### ISSUE THREAD

**Issue by Allain55** [farzher/fuzzysort#99]
If the search and target params equals but there are spaces in them than the single methods result won't be 0

`fuzzysort.single('some string that contains my query.', 'some string that contains my query.'),`
result score: -188.9

`fuzzysort.single('somestringthatcontainsmyquery.', 'somestringthatcontainsmyquery.')`
result score: -0

**Comment by ahmednawaz10p** [comment]
facing same problem

**Comment by farzher** [comment]
i personally don't use spaces, that's why this feature is so bad
i think i have a good solution but if you can post examples where you're searching with spaces and it's causing issues, i'd like to test against those cases first to make sure my fix doesn't introduce new issues

**Comment by ahmednawaz10p** [comment]
Thanks for your response. In one of our test cases I am comparing the string `Vice President Customer Success` against `Customer Success` and `Vice President Customer Success`. It should give more score against `Vice President Customer Success` ( score = -100.4 ) but instead it says it is more relevant to `Customer Success` ( score = -50 ) which should be the other way round

**Comment by farzher** [comment]
> Thanks for your response. In one of our test cases I am comparing the string `Vice President Customer Success` against `Customer Success` and `Vice President Customer Success`. It should give more score against `Vice President Customer Success` ( score = -100.4 ) but instead it says it is more relevant to `Customer Success` ( score = -50 ) which should be the other way round

oops sorry i deleted my comment because i quickly realized how obvious the answer was.
that said, your use case actually isn't supported and i'd expect lots of bad results!
this library tells you what results best match your search. it doesn't tell you what searches best match a target.

**Comment by ahmednawaz10p** [comment]
yeah understandable. However since we have the option of getting a score on string match. comparing a string with it self should give a score of zero as it is an exact match

**Comment by farzher** [comment]
> comparing a string with it self should give a score of zero as it is an exact match ( and a substring should have a less score )

yeah i agree and i'll fix that. but scores from this algo can't be compared that way. it's called fuzzysort instead of fuzzyscore for a reason.

the score is based on the amount of mistakes. so the more specific your search is, the more potential for mistakes, and the worse the score will be

```js
target = 'The Amazing Spider-Man™ - Lizard Rampage Pack'
fuzzysort.single('spider lizard', target).score // -81.8
fuzzysort.single('the spider lizard', target).score // -123.9
```

**Comment by farzher** [comment]
this is probably a dumb way of scoring things, but it's very fast, and not an issue when all results are being compared against the same search

**Comment by cedeber** [comment]
@farzher You fix broke the app, see my comment on the commit https://github.com/farzher/fuzzysort/commit/5b5a23e4a8ea4771f95abc19eba65643f2eeb874#r88860784

**Comment by farzher** [comment]
> @farzher You fix broke the app, see my comment on the commit [5b5a23e#r88860784](https://github.com/farzher/fuzzysort/commit/5b5a23e4a8ea4771f95abc19eba65643f2eeb874#r88860784)

what's broken? seems fine

**Comment by cedeber** [comment]
You are calling a function with an assignment as parameter. When you call `fuzzysort.single("with space", "whater")` it crashes with `allowSpaces is not defined`

**Comment by cedeber** [comment]
It did not happen in your tests because the variables is hoisted. You need to add `"use strict";` in `fuzzysort.js` and run the tests again to see it. This is also the default behavior in an ES modules env.

**Comment by farzher** [comment]
> It did not happen in your tests because the variable is hoisted. You need to add `"use strict";` in `fuzzysort.js` and run the tests again to see it. This is also the default behavior in an ES modules env.

ty, you probably saved a lot of people a lot of trouble

**Comment by cedeber** [comment]
No problems. Thanks for the quick update.
